% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Oct-2020 10:52:02
%  MATLAB version: 9.8.0.1396136 (R2020a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

A = 1;

E = saveVarsMat.E; % <1x1001 double> too many elements

IC = [2 3];

Y = saveVarsMat.Y; % <5001x2 double> too many elements

Y1 = saveVarsMat.Y1; % <6001x2 double> too many elements

Ya = saveVarsMat.Ya; % <1001x2 double> too many elements

ans = -0.54393031102984479;

f = saveVarsMat.f; % <1x1 function_handle> unsupported class

i = 6000;

ijk = 0.00012147328247913425;

interval = [0 10];

m = 6000;

x = saveVarsMat.x; % <6001x1 double> too many elements

xa = saveVarsMat.xa; % <1x1001 double> too many elements

clear saveVarsMat;
